services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: beatriz
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ingles
    ports:
      - "5433:5432"
    volumes:
      - ./db_data:/var/lib/postgresql
  adminer:
    image: adminer
    ports:
      - "8080:8080"
